//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algorytmy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Algorytmy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gattcgtcgtttaggtatcggtttgcagatatccccatcaccgaaatctggtcacctcta cagagaagcgaacctactcatcccctttgttagaagtccgcttggtcttaagccaaaggt catgtctcccgtttacattcctattaggccccgaggtgcagcactacgcaccccgaaccc ggatgtaagtttgacttagaggggccggacagacgccgtcgagtttaggactattaaatg tttctgcacttgcggtgattgactcgttgccggggggcctttaatcattagcaaagtcgt gaagctaggagcgggtagttttctgtgagtgactcgcaaaggccccgcagtccatgcgcg atcagatctcggtgatttgccacccaaaaacttctgggcgtctcgtatctcctccgtcat tgacggcttgcccgacgttttcccctgtggctatttttaacaatccatcgcctacgccca tcactcaagtatttcttggcagcc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DNA {
            get {
                return ResourceManager.GetString("DNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Księga pierwsza
        ///
        ///
        ///
        ///Gospodarstwo
        ///
        ///Powrót panicza — Spotkanie się pierwsze w pokoiku, drugie u stołu — Ważna Sędziego nauka o grzeczności — Podkomorzego uwagi polityczne nad modami — Początek sporu o Kusego i Sokoła — Żale Wojskiego — Ostatni Woźny Trybunału — Rzut oka na ówczesny stan polityczny Litwy i Europy
        ///
        ///    Litwo! Ojczyzno moja! ty jesteś jak zdrowie:
        ///Ile cię trzeba cenić, ten tylko się dowie,
        ///Kto cię stracił. Dziś piękność twą w całej ozdobie
        ///Widzę i opisuję, bo tęsknię po tobie.
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tadek {
            get {
                return ResourceManager.GetString("Tadek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJAPV\PYYhWJdeD]PBCeaecSQ\XRHMZPCMMMYHURgCMD_GKAMSgdR|iBGU{vJ_in|wW_ilEl{U[cGb`p|ooDcwIdtvFDCiEr_TzdCUVJ_KhlbGxbrLvXleKEopgofBjRQfDodxnhYfbYPYBn{aNtpiFvJvrOjc`]^V\yCI{v[N{GDoqWnvqFpr^d`JfjG_{rFEwvzFkrcUZck{sWE\^qo[ihutYu`QoyPIA{uwYhK{_\YxvaTPehAJDgXOBGirSSb^Tb{u_JCrfqyNPyzubPhHxFFWcfvS|UhMvxdUc[m[fL`OkK|EIqPCg[bN]dRvQlsQJlUTUfRH`M^lbshYfqJKFec\VWt{ItKvVPF|sil``I`ZyrifyvP\bhLaJvz{nS{hCeWSnicyFghyFI_`kOCPdkTjDarzlnoMKtXU\VtPTSWxAP\AWZQ_QkEUQiPMsfNTt[nNnKEUWoxQTXjpFqcR]Py\pDDoGgZkECDb^NPMUxI^ppAu{\HBCyte^S[kGR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tekstLosowy {
            get {
                return ResourceManager.GetString("tekstLosowy", resourceCulture);
            }
        }
    }
}
